use RecordReport;
DROP TABLE IF EXISTS rr_baseinfo;
create TABLE rr_baseinfo (
    id varchar(30) not null,
    patientid  varchar(20) not null,
    fullname varchar(20),
    sex  varchar(1),
    birthday   date,
    nation   varchar(10),
    createDate    date,
    cardno   varchar(18),
    address   varchar(100),
    marriage   varchar(10),
    height   float,
    weight   float,
    bmi   float,
    phone   varchar(20),
    temperature   float,
    bloodpressure   varchar(10),
    heartrate   int,
    breathe   int,
    symptom   varchar(200),
    symptomOther   varchar(100),
    familyHistory   varchar(200),
    ai01   varchar(10),
    ai02   varchar(60),
    ai03   date,
    ai04   varchar(60),
    ai11   varchar(10),
    ai12   varchar(60),
    ai13   date,
    ai14   varchar(60),
    p1   varchar(4),
    p1Date   date,
    p1One   varchar(4),
    p1OneDate   date,
    p2   varchar(4),
    p201Diagnose   varchar(60),
    p201Date   date,
    p201Status   varchar(60),
    p202Diagnose   varchar(60),
    p202Date   date,
    p202Status   varchar(60),
    p3   varchar(4),
    p301Diagnose   varchar(60),
    p301Date   date,
    p301Name   varchar(60),
    p302Diagnose   varchar(60),
    p302Date   date,
    p302Name   varchar(60),
    p4   varchar(4),
    p401Name   varchar(60),
    p401Date   date,
    p401Usage   varchar(60),
    p402Name   varchar(60),
    p402Date   date,
    p402Usage   varchar(60),
    p5   varchar(4),
    p5Name   varchar(60),
    h1   varchar(10),
    h1Years   int,
    h1Few   int,
    h2   varchar(10),
    h2Text   varchar(60),
    h3   varchar(10),
    h3Time   varchar(60),
    h4   varchar(4),
    h4Many  varchar(20),
    h5   varchar(20),
    h6   varchar(4),
    h6Date   date,
    h6Days   int,
    others   varchar(60),
    treat   varchar(60),
    nursename   varchar(10),
    status    varchar(2)
);

DROP TABLE IF EXISTS rr_followup_record;
create TABLE rr_followup_record (
    id varchar(30) not null,
    patientid  varchar(20) not null,
    visitDate  date,
    visitor  varchar(20),
    temperature  FLOAT ,
    selfReported  varchar(200),
    publicity  varchar(200),
    createDate date,
    status   varchar(2)
);

DROP TABLE IF EXISTS rr_plan_record;
create TABLE rr_plan_record (
    id varchar(30) not null,
    patientid  varchar(20) not null,
    examDate  date,
    examItems varchar(200),
    explanation  varchar(500),
    suggestion  varchar(500),
    plan1  varchar(100),
    plan2  varchar(100),
    plan3  varchar(100),
    plan1Date  date,
    plan2Date  date,
    plan3Date  date,
    nurseName  varchar(20),
    expertName  varchar(20),
    explantDate  date,
    createDate   date,
    status   varchar(2)
);